# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'RxSwift_HelloWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_HelloWorld
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
